// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Task {
    "id": string;
    "title": string;
    "detail": string;
    "isCompleted": boolean;
}

export interface TaskGroup {
    "id": string;
    "name": string;
    "tasks": Task[] | null;
}
